name: Build Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.5.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v5.1.0
        with:
            python-version: ${{ matrix.python-version }}

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 #v2
        with:
          pandoc-version: '3.1.11' # The pandoc version to download (if necessary) and use.

      - name: Test pandoc
        run: echo "# Test" | pandoc -t html

        # See https://docs.github.com/en/actions/tutorials/build-and-test-code/python
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            
      - name: Build documentation using Hatch
        run: |
            python -m pip install ipython
            hatch run docs:build
