name: Build Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.5.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v5.1.0
        with:
            python-version: ${{ matrix.python-version }}

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@a51a8012b0aab7c32ef9d19bf54da93f3254335e #v2
        with:
          pandoc-version: '3.1.11' # The pandoc version to download (if necessary) and use.

      - name: Test pandoc
        run: echo "# Test" | pandoc -t html

      # See https://docs.github.com/en/actions/tutorials/build-and-test-code/python
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install ipython
            python -m pip install -r requirements.txt
            
      - name: Build documentation using Hatch
        run: |
            hatch run docs:build
